DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
DATABASES['default']['NAME'] = 'nextcloudappstore'
DATABASES['default']['USER'] = 'nextcloudappstore'
DATABASES['default']['PASSWORD'] = 'nextcloudappstore'
DATABASES['default']['PORT'] = '5432'
DATABASES['default']['HOST'] = '127.0.0.1'
