version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry==1.6.1
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs


sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#   - pdf
#   - epub
