# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_app_discussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Full name')),
                ('homepage', models.URLField(blank=True, max_length=256, verbose_name='Homepage')),
                ('mail', models.EmailField(blank=True, max_length=128, verbose_name='E-Mail')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='apps', to='core.AppAuthor', verbose_name='App authors'),
        ),
    ]
