# Generated by Django 1.10.2 on 2016-10-05 14:24
#
#SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
#SPDX-License-Identifier: AGPL-3.0-or-later

import django.db.models.deletion
from django.db import migrations, models


def create_default_changelogs(apps, schema_editor):
    model = apps.get_model('core', 'AppRelease')
    model_trans = apps.get_model('core', 'AppReleaseTranslation')
    for release in model.objects.all():
        model_trans.objects.create(
            master_id=release.pk,
            language_code='en',
            changelog=''
        )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20161005_1424'),
    ]

    operations = [
        migrations.RunPython(create_default_changelogs,
                             migrations.RunPython.noop)
    ]
