# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160723_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(help_text='app id, identical to folder name', max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='appauthor',
            name='mail',
            field=models.EmailField(blank=True, max_length=256, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='appauthor',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='php_version_spec',
            field=models.CharField(max_length=256, verbose_name='PHP version requirement'),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='platform_version_spec',
            field=models.CharField(max_length=256, verbose_name='Platform version requirement'),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='version',
            field=models.CharField(help_text='Version follows Semantic Versioning', max_length=256, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='apptranslation',
            name='name',
            field=models.CharField(help_text='Rendered app name for users', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='apptranslation',
            name='summary',
            field=models.CharField(help_text="Short text describing the app's purpose", max_length=256, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(help_text='Category id which is used to identify a category. Used to identify categories when uploading an app', max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(help_text='Category name which will be presented to the user', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='database',
            name='id',
            field=models.CharField(help_text='Key which is used to identify a database', max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(help_text='Database name which will be presented to the user', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='databasedependency',
            name='version_spec',
            field=models.CharField(max_length=256, verbose_name='Database version requirement'),
        ),
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.CharField(help_text='Key which is used to identify a license', max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(help_text='License name which will be presented to the user', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='phpextension',
            name='id',
            field=models.CharField(help_text='e.g. libxml', max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='PHP extension'),
        ),
        migrations.AlterField(
            model_name='phpextensiondependency',
            name='version_spec',
            field=models.CharField(max_length=256, verbose_name='Extension version requirement'),
        ),
        migrations.AlterField(
            model_name='shellcommand',
            name='name',
            field=models.CharField(help_text='Name of a required shell command, e.g. grep', max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Shell Command'),
        ),
    ]
