# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160723_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appauthor',
            options={'verbose_name': 'App Author', 'verbose_name_plural': 'App Authors'},
        ),
    ]
