# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_migrate_changelogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appownershiptransfer',
            options={'verbose_name': 'App ownership transfer', 'verbose_name_plural': 'App ownership transfers'},
        ),
    ]
