# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20160828_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.5, verbose_name='Rating')),
                ('rated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='rating_overall',
            field=models.FloatField(default=0.5, verbose_name='Overall rating'),
        ),
        migrations.AddField(
            model_name='app',
            name='rating_recent',
            field=models.FloatField(default=0.5, verbose_name='Recent rating'),
        ),
        migrations.AddField(
            model_name='apprating',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='core.App', verbose_name='App'),
        ),
        migrations.AddField(
            model_name='apprating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='apprating',
            unique_together=set([('app', 'user')]),
        ),
    ]
