# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161005_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appreleasedeletelog',
            options={'verbose_name': 'App release deletion', 'verbose_name_plural': 'App release deletions'},
        ),
        migrations.RemoveField(
            model_name='app',
            name='discussion',
        ),
    ]
