# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20160828_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.5, help_text='Rating from 0.0 (worst) to 1.0 (best)', verbose_name='Rating')),
                ('rated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'App Rating',
                'verbose_name_plural': 'App Ratings',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AppRatingTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('comment', models.TextField(default='', help_text='Rating comment in Markdown', verbose_name='Rating comment')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.AppRating')),
            ],
            options={
                'managed': True,
                'db_tablespace': '',
                'db_table': 'core_apprating_translation',
                'verbose_name': 'App Rating Translation',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='app',
            name='rating_overall',
            field=models.FloatField(default=0.5, verbose_name='Overall rating'),
        ),
        migrations.AddField(
            model_name='app',
            name='rating_recent',
            field=models.FloatField(default=0.5, verbose_name='Recent rating'),
        ),
        migrations.AddField(
            model_name='apprating',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.App', verbose_name='App'),
        ),
        migrations.AddField(
            model_name='apprating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='appratingtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='apprating',
            unique_together=set([('app', 'user')]),
        ),
    ]
