# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 12:35
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_nightlies(apps, schema_editor):
    release_model = apps.get_model('core', 'AppRelease')
    for row in release_model.objects.filter(version__endswith='-nightly'):
        row.is_nightly = True
        row.version = row.version.split('-')[0]
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20161013_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='is_nightly',
            field=models.BooleanField(default=False, verbose_name='Nightly'),
        ),
        migrations.AlterUniqueTogether(
            name='apprelease',
            unique_together=set([('app', 'version', 'is_nightly')]),
        ),
        migrations.RunPython(migrate_nightlies, migrations.RunPython.noop)
    ]
