# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160828_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apprating',
            options={'verbose_name': 'App Rating', 'verbose_name_plural': 'App Ratings'},
        ),
    ]
