# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160903_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apprating',
            options={'ordering': ('-rated_at',), 'verbose_name': 'App Rating', 'verbose_name_plural': 'App Ratings'},
        ),
        migrations.AddField(
            model_name='app',
            name='last_release',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Last release at'),
        ),
    ]
