# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160828_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprating',
            name='comment',
            field=models.TextField(default='', verbose_name='Rating comment'),
        ),
    ]
