# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apprelease_is_nightly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
