# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_apprating_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRatingTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('comment', models.TextField(default='', verbose_name='Rating comment')),
            ],
            options={
                'verbose_name': 'App Rating Translation',
                'managed': True,
                'db_table': 'core_apprating_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='apprating',
            name='comment',
        ),
        migrations.AddField(
            model_name='appratingtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.AppRating'),
        ),
        migrations.AlterUniqueTogether(
            name='appratingtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
