# Generated by Django 1.10.3 on 2016-11-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161104_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextcloudRelease',
            fields=[
                ('version', models.CharField(help_text='e.g. 9.0.54', max_length=100, primary_key=True, serialize=False, verbose_name='Nextcloud version')),
                ('is_current', models.BooleanField(default=False, help_text='Only one version is allowed to be the current version. This field is used to pre-select drop downs for app generation etc.', verbose_name='Is current version')),
            ],
            options={
                'verbose_name_plural': 'Nextcloud releases',
                'verbose_name': 'Nextcloud release',
            },
        ),
    ]
