# Generated by Django 1.10.3 on 2016-11-28 19:02
#
#SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
#SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_nextcloudrelease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nextcloudrelease',
            options={'ordering': ('-version',), 'verbose_name': 'Nextcloud release', 'verbose_name_plural': 'Nextcloud releases'},
        ),
        migrations.AddField(
            model_name='screenshot',
            name='small_thumbnail',
            field=models.URLField(default='', max_length=256, verbose_name='Small thumbnail'),
        ),
        migrations.AlterField(
            model_name='app',
            name='rating_num_overall',
            field=models.IntegerField(default=0, verbose_name='Number of overall submitted ratings'),
        ),
        migrations.AlterField(
            model_name='app',
            name='rating_num_recent',
            field=models.IntegerField(default=0, verbose_name='Number of recently submitted ratings'),
        ),
    ]
