# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20161128_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ownership_transfer_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, a user can try to register the same app again using the public certificate and signature. If he does, the app will be transferred to him.', verbose_name='Ownership transfer enabled'),
        ),
    ]
