# Generated by Django 1.11.3 on 2017-08-09 08:03
#
#SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors
#SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_auto_20170610_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='signature_digest',
            field=models.CharField(default='sha512', max_length=256,
                                   verbose_name='Signature hashing algorithm'),
            preserve_default=False,
        ),
    ]
