# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_apprelease_signature_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='discussion',
            field=models.URLField(blank=True, max_length=256, verbose_name='Forum'),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='signature',
            field=models.TextField(help_text="A signature using the app's certificate", verbose_name='Signature'),
        ),
    ]
