# Generated by Django 1.11.6 on 2017-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170811_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextcloudrelease',
            name='has_release',
            field=models.BooleanField(default=False, help_text='If true, this is an actual released Nextcloud version that can be downloaded as an archive. If false, the release is either a pre-release, or not available for download anymore.', verbose_name='Has a release'),
        ),
    ]
