# Generated by Django 2.2.11 on 2020-04-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200328_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Used to approve integrations'),
        ),
    ]
