# Generated by Django 3.2 on 2022-08-08 09:08
#
#SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
#SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_app_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appauthor',
            name='mail',
            field=models.EmailField(blank=True, max_length=256, verbose_name='Email'),
        ),
    ]
