# Generated by Django 4.2.5 on 2023-09-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_appauthor_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='aa_is_system',
            field=models.BooleanField(default=False, help_text='Whether the application is system-wide (i.e. can impersonate the user without him interacting with the application)', verbose_name='AppAPI system app flag'),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='aa_proto',
            field=models.CharField(blank=True, db_index=True, default='', help_text='If empty, then this is a release of a regular application; any other value indicates the application protocol for the AppAPI system', max_length=8, verbose_name='AppAPI communication protocol'),
        ),
        migrations.CreateModel(
            name='AppApiReleaseDeployMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_type', models.CharField(max_length=64, verbose_name='Deploy Identifier')),
                ('install_data', models.CharField(help_text='JSON data for AppAPI installer depending on installation type', max_length=1024, verbose_name='Installer specific data')),
                ('app_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_methods', to='core.apprelease', verbose_name='App release')),
            ],
            options={
                'db_table': 'core_appapi_release_deploy_method',
            },
        ),
        migrations.CreateModel(
            name='AppApiReleaseApiScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.BooleanField(default=False, help_text='Is it possible for the application to work without this API group?', verbose_name='Is scope optional')),
                ('scope_name', models.CharField(max_length=32, verbose_name='Name of the API scope')),
                ('app_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_scopes', to='core.apprelease', verbose_name='App release')),
            ],
            options={
                'db_table': 'core_appapi_release_api_scopes',
            },
        ),
    ]
