# Generated by Django 4.2.6 on 2023-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_apprelease_aa_is_system_apprelease_aa_proto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Heading')),
                ('excerpt', models.CharField(max_length=512, verbose_name='Excerpt')),
                ('link', models.CharField(max_length=256, unique=True, verbose_name='Link')),
                ('image', models.CharField(max_length=256, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Nextcloud Podcast',
                'verbose_name_plural': 'Nextcloud Podcasts',
            },
        ),
        migrations.AlterModelOptions(
            name='appapireleaseapiscope',
            options={'verbose_name': 'AppAPI release API Scope', 'verbose_name_plural': 'AppAPI release API Scopes'},
        ),
        migrations.AlterModelOptions(
            name='appapireleasedeploymethod',
            options={'verbose_name': 'AppAPI release Deploy method', 'verbose_name_plural': 'AppAPI release Deploy methods'},
        ),
    ]
