# Generated by Django 4.2.7 on 2023-12-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_podcast_alter_appapireleaseapiscope_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprating',
            name='appeal',
            field=models.BooleanField(default=False, verbose_name='Appeal'),
        ),
    ]
