# Generated by Django 4.2.7 on 2023-12-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_podcast_alter_appapireleaseapiscope_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprating',
            name='appeal',
            field=models.BooleanField(default=False, verbose_name='Appeal'),
        ),
        migrations.AlterField(
            model_name='apprating',
            name='rated_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='AppRatingDeleteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'App rating deletion',
                'verbose_name_plural': 'App rating deletions',
            },
        )
    ]
