# Generated by Django 4.2.8 on 2024-01-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_apprating_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprating',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='apprating',
            name='rated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
