# Generated by Django 4.2.9 on 2024-01-31 10:53
#
#SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
#SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_apprating_last_modified_alter_apprating_rated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appapireleaseapiscope',
            name='optional',
        ),
    ]
