# Generated by Django 4.2.9 on 2024-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_appapireleaseapiscope_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprelease',
            name='aa_proto',
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='aa_is_system',
            field=models.BooleanField(default=None, null=True, help_text='Whether the application is system-wide (i.e. can impersonate the user without him interacting with the application)', verbose_name='AppAPI system app flag'),
        ),
    ]
