# Generated by Django 4.2.14 on 2024-07-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_apprelease_aa_proto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_orphan',
            field=models.BooleanField(default=False, verbose_name='Orphan'),
        ),
    ]
