# Generated by Django 4.2.14 on 2024-08-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_app_is_orphan'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_enterprise_supported',
            field=models.BooleanField(default=False, verbose_name='Enterprise supported'),
        ),
    ]
