# Generated by Django 4.2.14 on 2024-08-13 04:14
#
#SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
#SPDX-License-Identifier: AGPL-3.0-or-later

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_app_is_enterprise_supported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256, verbose_name='Donation URL')),
                ('type', models.CharField(default='other', max_length=256, verbose_name='Donation Type')),
                ('title', models.CharField(default='Donate to support this app', max_length=256, verbose_name='Donation Title')),
                ('ordering', models.IntegerField(verbose_name='Ordering')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.app', verbose_name='App')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['ordering'],
            },
        ),
    ]
