# Generated by Django 4.2.30 on 2026-05-14 22:00
#
#SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
#SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_appapi_deploy_env_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='Deprecated'),
        ),
    ]
