# Generated by Django 4.2.30 on 2026-07-14 20:35
#
#SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
#SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_app_is_deprecated"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="is_enterprise_only",
            field=models.BooleanField(default=False, verbose_name="Enterprise only"),
        ),
    ]
