# Generated by Django 4.2.30 on 2026-09-16 19:40
#
# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="apprelease",
            name="release_date",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Optional, app store administrators only. Shown instead of the upload timestamp where the two "
                    "differ. Purely presentational: it is not used for caching, ordering or the API."
                ),
                null=True,
                verbose_name="Release date",
            ),
        ),
    ]
