# Generated by Django 4.2.30 on 2026-09-16 20:10
#
# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_apprelease_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="release_date",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Optional, app store administrators only. Shown as the last update date instead of the last "
                    "release, which integrations never set because they do not upload releases. Purely "
                    "presentational: it is not used for caching, ordering or the API."
                ),
                null=True,
                verbose_name="Release date",
            ),
        ),
    ]
