sudo: false
dist: trusty
language: php

php:
    - 5.6
    - 7
    - 7.1

env:
    global:
        - APP_NAME={{ app.id }}
        - CORE_BRANCH=stable{{ app.nextcloud_version }}
    matrix:
        - DB=pgsql

matrix:
    allow_failures:
        - env: DB=pgsql CORE_BRANCH=master
    include:
        - php: 5.6
          env: DB=sqlite
        - php: 5.6
          env: DB=mysql
        - php: 5.6
          env: DB=pgsql CORE_BRANCH=master
    fast_finish: true

addons:
    firefox: 'latest'
    mariadb: '10.1'
    apt:
        packages:
            - libxml2-utils

services:
    - postgresql
    - mariadb

before_install:
    # enable a display for running JavaScript tests
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - nvm install 8
    - npm install -g npm@latest
    - make
    - make appstore
    # install core
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
    - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
    - cd ../server
    - ./occ app:enable $APP_NAME

before_script:
    # start webserver
    - php -S localhost:8080 &
    - cd apps/$APP_NAME

script:
    # check info.xml schema validity
    - wget https://apps.nextcloud.com/schema/apps/info.xsd
    - xmllint appinfo/info.xml --schema info.xsd --noout
    # execute tests
    - make test

after_failure:
    - cat ../../data/nextcloud.log
