# Generated by Django 4.2.30 on 2026-05-14 22:00
#
# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="subscribe_to_news",
            field=models.BooleanField(
                default=False, help_text="User has opted in to receive Nextcloud news and updates."
            ),
        ),
    ]
