# Generated by Django 4.2.30 on 2026-08-25 18:24
#
# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_userprofile_subscribe_to_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="video_autoplay",
            field=models.BooleanField(
                default=False, help_text="User has opted in to autoplay videos on app detail pages."
            ),
        ),
    ]
