# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: "Pull Request Docs Check"

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  appstore_docs:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'

      - name: Install poetry
        run: pip install poetry==1.8.2

      - name: Install dependencies
        run: poetry install --with docs

      - name: Build docs
        run: make docs

      - name: Pack the results in local tar file
        shell: bash
        run: tar czf /tmp/documentation.tar.gz -C docs/_build/html .

      - name: Upload static documentation
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Appstore docs.zip
          path: "/tmp/documentation.tar.gz"
